import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  curriculumSidebar: [
    'intro',
    {
      type: 'html',
      value: '<div class="sidebar-divider"><span>Foundations</span></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Module 01 — Kotlin Foundation',
      collapsed: true,
      items: [
        'kotlin-foundation/overview',
        'kotlin-foundation/coroutines-deep-dive',
        'kotlin-foundation/advanced-patterns',
      ],
    },
    {
      type: 'category',
      label: 'Module 02 — Android Fundamentals',
      collapsed: true,
      items: [
        'android-fundamentals/overview',
        'android-fundamentals/activity-fragment-lifecycle',
        'android-fundamentals/intents-pendingintent',
        'android-fundamentals/broadcast-content-providers',
        'android-fundamentals/resources-localization',
      ],
    },
    {
      type: 'category',
      label: 'Module 03 — Jetpack Compose',
      collapsed: true,
      items: [
        'jetpack-compose/overview',
        'jetpack-compose/state-side-effects',
        'jetpack-compose/theming-design-systems',
        'jetpack-compose/lists-lazy-layouts',
        'jetpack-compose/navigation',
        'jetpack-compose/animations',
        'jetpack-compose/forms-text-input',
        'jetpack-compose/custom-layouts-gestures',
        'jetpack-compose/modifiers-deep-dive',
        'jetpack-compose/testing',
        'jetpack-compose/interop',
        'jetpack-compose/performance',
        'jetpack-compose/internals',
      ],
    },
    {
      type: 'category',
      label: 'Module 04 — Architecture & Patterns',
      collapsed: true,
      items: [
        'architecture-patterns/overview',
        'architecture-patterns/mvi-state-machines',
        'architecture-patterns/offline-first',
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"><span>Data & Services</span></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Module 05 — Data & Persistence',
      collapsed: true,
      items: [
        'data-persistence/overview',
        'data-persistence/room-deep-dive',
        'data-persistence/datastore',
        'data-persistence/encrypted-storage',
        'data-persistence/files-and-media',
      ],
    },
    {
      type: 'category',
      label: 'Module 06 — Networking & API',
      collapsed: true,
      items: [
        'networking-api/overview',
        'networking-api/graphql-websocket-grpc',
      ],
    },
    {
      type: 'category',
      label: 'Module 07 — Firebase & Cloud',
      collapsed: true,
      items: [
        'firebase-cloud/overview',
        'firebase-cloud/auth-deep-dive',
        'firebase-cloud/firestore-deep-dive',
        'firebase-cloud/cloud-storage-fcm',
        'firebase-cloud/remote-config-app-check',
      ],
    },
    {
      type: 'category',
      label: 'Module 08 — Advanced Components',
      collapsed: true,
      items: [
        'advanced-components/overview',
        'advanced-components/workmanager',
        'advanced-components/services-notifications',
        'advanced-components/permissions-biometric',
        'advanced-components/camerax-sensors',
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"><span>Quality & Performance</span></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Module 09 — Testing & Quality',
      collapsed: true,
      items: [
        'testing-quality/overview',
        'testing-quality/unit-testing',
        'testing-quality/instrumentation-testing',
        'testing-quality/tdd-coverage',
        'testing-quality/benchmark-property-based',
      ],
    },
    {
      type: 'category',
      label: 'Module 10 — Performance',
      collapsed: true,
      items: [
        'performance/overview',
        'performance/baseline-profiles',
      ],
    },
    {
      type: 'category',
      label: 'Module 11 — Publishing',
      collapsed: true,
      items: [
        'publishing/overview',
        'publishing/play-console-releases',
        'publishing/play-billing',
        'publishing/app-bundles',
      ],
    },
    {
      type: 'category',
      label: 'Module 12 — Advanced & Trending',
      collapsed: true,
      items: [
        'advanced-trending/overview',
        'advanced-trending/kmp-deep-dive',
        'advanced-trending/compose-multiplatform',
        'advanced-trending/wear-health',
        'advanced-trending/tv-auto-ble-xr',
      ],
    },
    {
      type: 'category',
      label: 'Module 13 — Version Control',
      collapsed: true,
      items: ['version-control/overview'],
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"><span>Enterprise Engineering</span></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Module 14 — Gradle & Build Systems',
      collapsed: true,
      items: [
        'gradle-build/overview',
        'gradle-build/convention-plugins',
      ],
    },
    {
      type: 'category',
      label: 'Module 15 — Modularization at Scale',
      collapsed: true,
      items: [
        'modularization/overview',
        'modularization/konsist-dynamic-features',
      ],
    },
    {
      type: 'category',
      label: 'Module 16 — Security & Compliance',
      collapsed: true,
      items: [
        'security-compliance/overview',
        'security-compliance/cryptography-keystore',
        'security-compliance/play-integrity',
      ],
    },
    {
      type: 'category',
      label: 'Module 17 — CI/CD & DevOps',
      collapsed: true,
      items: [
        'cicd-devops/overview',
        'cicd-devops/github-actions',
      ],
    },
    {
      type: 'category',
      label: 'Module 18 — Observability',
      collapsed: true,
      items: [
        'observability/overview',
        'observability/opentelemetry',
      ],
    },
    {
      type: 'category',
      label: 'Module 19 — Enterprise UX',
      collapsed: true,
      items: [
        'enterprise-ux/overview',
        'enterprise-ux/design-systems',
        'enterprise-ux/accessibility',
      ],
    },
    {
      type: 'category',
      label: 'Module 20 — Career & Interview',
      collapsed: true,
      items: [
        'career-interview/overview',
        'career-interview/system-design-walkthroughs',
      ],
    },
    {
      type: 'category',
      label: 'Module 21 — AI & On-Device ML',
      collapsed: true,
      items: [
        'ai-ml/overview',
        'ai-ml/gemini-nano',
        'ai-ml/ml-kit-tensorflow',
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"><span>Platform Primitives</span></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Graphics, Media & Power',
      collapsed: true,
      items: [
        'graphics-media/overview',
        'graphics-media/graphics-rendering',
        'graphics-media/media3-exoplayer',
        'graphics-media/battery-power',
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"><span>Capstone Projects</span></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Capstone Projects',
      collapsed: true,
      items: [
        'projects/overview',
        'projects/ecommerce',
        'projects/social-media',
        'projects/food-delivery',
        'projects/fitness-tracker',
        'projects/news-aggregator',
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"><span>Reference</span></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Architecture Guide',
      collapsed: true,
      items: [
        'architecture/overview',
        'architecture/clean-architecture',
        'architecture/hexagonal-ports-adapters',
        'architecture/unidirectional-data-flow',
        'architecture/dependency-injection',
        'architecture/error-handling',
        'architecture/domain-modeling',
        'architecture/project-structure',
      ],
    },
    {
      type: 'category',
      label: 'Design Patterns',
      collapsed: true,
      items: [
        'patterns/design-patterns',
        'patterns/creational-patterns',
        'patterns/structural-patterns',
        'patterns/behavioral-patterns',
        'patterns/concurrency-patterns',
        'patterns/data-patterns',
        'patterns/kotlin-idiomatic-patterns',
        'patterns/state-patterns',
        'patterns/component-patterns',
      ],
    },
  ],
};

export default sidebars;
